### ISSUE TITLE
WhiteCommonCallbacks error 

### ISSUE THREAD

**Issue by DevDragonLi** [netless-io/Whiteboard-iOS#87]
#import "DWKWebView" =>  #import <NTLBridge/DWKWebView.h>

**Comment by vince-hz** [comment]
Thanks for your proposal.

It has been fixed in this [commit](https://github.com/netless-io/Whiteboard-iOS/commit/78c4ce10a503612dd79dab3bbb4b2d547b2f2067) . And it will be released at next patch version.

README has been updated for the explaination. You can click [here](https://github.com/netless-io/Whiteboard-iOS/commit/ef72debde4c4e5ae2df9416be904eede710f3e22) .
